---
title: 'Project Proposal - CSR Naloxone'
author: 'STAT 245, Fall 2020 (Group Members: Nana Ama Baidoo, Alex Visser, Joshua Ridder, Joseph Jinn)'
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document:
    fig_height: 8
    fig_width: 13
  html_document:
    fig_height: 8
    fig_width: 13
    df_print: paged
classoption: portrait
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggformula)
require(mosaic)
require(fastR2)
require(tidyverse)
require(s245)
```

# General Instructions
Create a shared RStudio project for your group (instructions in class on Friday 9/25). Make sure it is shared with Prof DR. Prepare your proposal in the form of an R Markdown document, and save it within your project. **You do not need to submit the proposal anywhere - simply make sure it's saved in your R project and I will review it there.**

The document should have one section for each question below. Your answers need not be long - the average proposal will probably be 1-2 pages in total. The goal is not to go into great detail, but to touch on all the key areas you need to plan. You can come back to this proposal throughout the project to gauge your progress, and revise *the proposal* or *what you are doing* as needed.

___
___


# Questions to answer

## 1. Project Partner
In a short paragraph, who is your project partner and what is their main mission? If appropriate, you may quote (with citation) from your contact person, partner organization website, etc. You can also use materials from the [project descriptions](https://rsconnect.calvin.edu:3939/content/108/) you were given.


Project Partner: Calvin University - The Center for Social Research 

>*We conduct social-scientific research projects, taking data from collection to reporting, through focus groups, statistical analyses, program evaluations, maps, interactive data visualizations, surveys and more.*

>*The Center conducts and collaborates on several large research projects and several dozen smaller projects annually for academic, public-sector, nonprofit, religious, and business organizations.*

Cited from: https://calvin.edu/centers-institutes/center-for-social-research/


Project Contacts:

* Keila Pieters: krp28@calvin.edu

* Laura Luchies: lbl7@calvin.edu


Project Name: **Center for Social Research - Naloxone Standing Order Project - CDC WONDER Data Project**

Project Description:

>"The Center for Social Research is working on evaluating Michigan’s state-wide naloxone standing order. Naloxone is a drug that reverses opioid overdose. An opioid can be a prescription opioid for pain like oxycodone or morphine or non-prescription like heroin.

>The standing order evaluation is part of the larger MODA (Michigan overdose data to action) initiative to combat the opioid epidemic. The US is currently considered to be in the third wave of the opioid epidemic (read more about the opioid epidemic at https://www.cdc.gov/drugoverdose/epidemic/index.html).

>So far, we have conducted interviews and focus groups with key people from a variety of fields who have experience with the standing order, opioid use disorder, recovery, harm reduction, etc. Through these interviews and focus groups, we have identified several key outcomes or goals the standing order should be accomplishing." 

Cited from: Documentation provided by Keila Pieters.

Dataset: "CDC Wonder Data"

https://wonder.cdc.gov/ucd-icd10.html


___
___

## 2. Goals and Deliverables

**This is the key section of the whole proposal.**

What questions will you be trying to answer in this project? Try to be as specific as possible (but concise is good). This can be a bulleted list. Aim for about 2-4 questions. 

Then, what materials will you produce to achieve these goals? Provide a second bulleted list. These "deliverables" are the things you will do/make/provide to your partner. Provide a list of the deliverables you and your partner would like to have.

A default option might include an analysis-ready version of the dataset and a report with graphics, tables, and statistical model conclusions. But consider what is right for your project: would a presentation, folder of image files with graphics, or interactive web dashboard be more useful than a report? Do people at the partner organization want to learn to do/replicate the analysis (maybe you provide an Rmd file and videos or written instructions)? Is your team trying to prepare a manuscript for a peer-reviewed journal (if so, maybe an outline or draft of the methods and results sections, or more, is the main deliverable)? 

I don't care if you write a report or not -- I want you to make things that are useful for your partner organization, using data, graphics, and regression models somehow. So in your initial meeting, do your best to discern what deliverables would be most needed.

**If possible, your partner should review the "Goals and Deliverables" section of your proposal, either before or after you submit it to me. Then, be sure to revise it with their feedback in mind.**


Research Question(s):

* Trends in overdose deaths in Kent County compared to other counties

+ Kent

+ Wayne

+ Ingham

+ Macomb

+ Washtenaw

* Do numbers seem to be increasing, decreasing, or staying the same after 2017?

* Consider creating a map and tracking it over time

* Does gender, age, or race seem to have an effect on overdose rate?

* Consider using metropolitan area as another variable.

* Compare cause of death including narcotics to non-narcotics. Has one increased as the other decreased over time? Have both increased/decreased?

* Anything else you find interesting!

Cited from: Documentation provided by Keila Pieters.

___

Deliverables:

* Data-set(s) containing all variables of interest that is required to re-run analysis code.
+ Essentially extract and JOIN disparate subsets of the whole data-set together due to limitations of initial data extraction from CDC website.
+ CSV format, in all likelihood.

* Data visualizations displaying any trends found in "night science" exploration of the data-set(s).
+ Probably R-based plots using R packages (some thoughts using D3.js to construct web app-based graphs - Joseph Jinn)
+ knit-to-PDF/HTML or individual PNG's.

* R-Markdown file containing all analysis code and written report detailing the analysis.
+ PDF/HTML version after knitting.

* GitHub repository containing all work done (tentative, if we decide to use version control).
+ If this route is chosen, all deliverables above will also be contained in the repository except possibly excluding data-set(s) (file size dependent) and image files (file size dependent).
+ Possibly store large data-set(s) and iamge files in OneDrive, Google Drive, Dropbox, etc., and share via links.

* More T.B.D.
+ ...
+ ...


___
___

## 3. Data
What data will you use? Do you already have it, and if not, when and how will you get it? What format is it in? 


Link: https://wonder.cdc.gov/ucd-icd10.html

The CDC website provides a GUI/dashboard by which you can extract subsets of the entire data-set.

*Unfortunately, there is no way to obtain the entire data-set as one file. (bypass issue by data wrangling and manipulation the individual data subsets)*

Format: CSV

___
___

## 4. Data Prep
Do you already know of specific tasks you will need to do to get your data in a format ready to read into R and prepared for analysis? If so, describe here. (Do you need to combine several datasets into one? Recode or rename variables, or compute new ones? Rearrange rows and columns?) If you do not know yet, just say so. Your answer to this question helps you look ahead at what needs to be done soon, and helps me prepare support materials for you to work with your data.

**TO BE DETERMINED.**

Initial task is to download subsets of the data-set from the CDC Wonder website and explore each before determining the exact form of the data we need for the analysis.


GROUP BY:

*	State
*	County (Kent county especially)
*	Drug/Alcohol Induced Cause 
*	Cause of death (search for keyword “narcotics”)
*	Gender
*	Race
*	Age

Filters:

* States (Michigan specially)
* Years (2012-2018)

Cited from: Documentation provided by Keila Pieters.


___
___

## 5. Background
What library, literature, or online resources will you need to consult to understand the context of your project? Identify 3 or more ideas and list them. Your partner may have suggestions; or you can ask from help from the Math/Science Hekman Library liaison, Katherine Swart (kswart20\@calvin.edu; Katherine’s online office hours are Tues. 1-3pm and Wed. 3-5pm. Simply text or chat from the library’s homepage during these times). 

Ideally, not all of your context resources will be web sites - consider whether there are films (documentary, TED talks, etc), books, or academic journal articles that are relevant. 

The idea is to reveiw these materials in the first weeks of your project to get familiar with the topic and understand what other data analysts are doing with similar data, not to do a full literature review or write anything up. One idea is to have different group members review different resources, and present/discuss them together at an early group meeting.

**WORK IN PROGRESS.**
* Medline PLus video (offers explanation of how Naloxone saves lives)
+ https://www.youtube.com/watch?v=cssRZEI9ujY&feature=youtu.be

* CDC Website:
+ https://wonder.cdc.gov/wonder/help/faq.html
+ https://wonder.cdc.gov/wonder/help/main.html
+ https://www.cdc.gov/drugoverdose/epidemic/index.html


___
___

## 6. Current Skills 
What skills and strengths do your group members bring to the project that are likely to be useful?  (This might include interpersonal skills and qualities like organization or leadership, or more practical skills like other software (GIS, Tableau, Excel, ...)) or specific R, data, or general coding experience.

**Nana Ama Baidoo**

* Tableau
* Excel
* Python (very basic)
* R (basic)
* Microsoft Office applications
* Organization
* Open-minded & Understanding

**Alex Visser**

* Excel
* Python
* Organization
* Communication
* R (Basic)
* Time management
* Creativity

**Joshua Ridder**

* Python/C++/C#
* R (basic)
* Excel/Word/Powerpoint
* GitHub
* Discord/Slack/Teams

**Joseph Jinn**

* Python/R/SQL (basic familiarity)
* GitHub/GitFlow, SourceTree - frontend for Git (version control tools)
* PyCharm, PHPStorm R-Studio (IDE's)
* Adobe Photoshop, InDesign (probably not relevant)
* Microsoft Word, Excel, PowerPoint
* Modo, Zbrush, Substance Painter (3D Modeling - irrelevant)
* Discord, Slack, M$ Teams (communicaiton platforms)
* Windows 10 OS (please don't ask me to work on MacOS or Linux)
* VSCode (text editor)
* SQL Server 2019 (very basic familiarity)
* Trello (project management tool - task assignment/priority/etc.)
* Caffeine


___
___

## 7. Work plan
Talk with your group about how you think you will work best. Will you divide tasks and then hold meetings to report on progress, or hold more frequent meetings to work collaboratively?  Do certain group members want to take the lead on certain tasks? What times will work for meetings outside class time, if they are needed? Just spend a little time thinking about how you will coordinate effort for the project, and write a brief summary of your initial plans.


**TO BE DETERMINED.**

* Initial plan to work on this project proposal.
* Next step is to download the data subsets and explore them in R, which will probably include some data wrangling and manipulation (and general "night science" EDA).
* Most likely team and partner meetings will remain purely virtual in nature via e-mail, Teams, etc.
* Schedule coordination will probably be a big hassle in synchronously working together, so we believe asynchronous work will be the modus operandi.
* Will schedule meeting(s) with project partner(s) as deemed necessary in order to obtain feedback as to current progress.


___
___

## 8. Requests
Is there anything else you expect you will need from me to complete your project? Please feel free to let me know so I can also plan ahead.

>Free and unlimited supply of caffeinated products.

On a more serious note, probably occasional coding assistance in R.

I (Joseph Jinn) will probably keep my own copies of project files in a personal GitHub Repository for my own edification (and just in case).

___
___

